# Use the toolchain shipped with the pinned CommonLib source.
get_filename_component(TTCG_SOURCE_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
if(NOT DEFINED XWIN_SYSROOT)
  if(DEFINED ENV{XWIN_SYSROOT})
    set(XWIN_SYSROOT "$ENV{XWIN_SYSROOT}")
  else()
    set(XWIN_SYSROOT "${TTCG_SOURCE_ROOT}/build/toolchain/xwin")
  endif()
endif()
set(ENV{XWIN_SYSROOT} "${XWIN_SYSROOT}")
if(DEFINED ENV{TESSERA_CLANG_CL})
  set(CMAKE_C_COMPILER "$ENV{TESSERA_CLANG_CL}" CACHE FILEPATH "C compiler" FORCE)
  set(CMAKE_CXX_COMPILER "$ENV{TESSERA_CLANG_CL}" CACHE FILEPATH "C++ compiler" FORCE)
endif()
if(DEFINED ENV{TESSERA_LLD_LINK})
  set(CMAKE_LINKER "$ENV{TESSERA_LLD_LINK}" CACHE FILEPATH "Linker" FORCE)
endif()
include("${TTCG_SOURCE_ROOT}/build/deps/commonlib/cmake/toolchain-linux-clangcl.cmake")
